<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository {

    //retourne la liste des sites de production qui ne correspondent pas au site courrant
    public function findSiteNotCurrent($id,$user) {
        //Création de la requête sql
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.id != :id')
           ->andWhere('s.user = :user')
           ->andWhere('s.main = :main')
           ->setParameters(['id'=> $id, 'user'=>$user,'main'=>false])
           ->orderBy('s.nom');
        
        //recuperation et retour du resultat de la requête
        $result = $qb->getQuery()->getResult();
        return $result;
    }

}
