<?php

namespace Geolocation\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CpfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpfRepository extends EntityRepository
{
    public function findCodeNafLike($term, $limit = 25) {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c.nom, s.libelle')
            ->innerJoin('Geolocation\AdminBundle\Entity\SousCategorie', 's', 'WITH', 'c.souscategorie = s.id')
            ->where('c.nom LIKE :term')
            ->orWhere('c.nom LIKE :termNoPoint')
            ->orWhere('s.libelle LIKE :term')
            ->setParameters(['term' => '%' . $term . '%', 'termNoPoint' => '%' . str_replace('.', '', $term) . '%'])
            ->setMaxResults($limit);

        $arrayAss = $qb->getQuery()
            ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = array("Codes" => $data['nom'] . ' ' . $data['libelle']);
        }

        return $array;
    }
}
