<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * DivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserExist()
    {
        $qb = $this->createQueryBuilder('d');
        $qb->join('GeolocationAdminBundle:Cpf', 'c', 'WITH', 'd.id = c.section')
            ->join('GeolocationAdminBundle:Ressources', 'r', 'WITH', 'c.id = r.cpf')
            ->groupBy('d.id');

        return $qb->getQuery()->getResult();
    }
}
