<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * IsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsoRepository extends \Doctrine\ORM\EntityRepository
{
}
