<?php

namespace Geolocation\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PilierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilierRepository extends EntityRepository
{
    public static function getCategorie () {
        return array(
            '0' => 'Gestion des déchets',
            '1' => 'Offre des acteurs économiques',
            '2' => 'Demande et comportement des consommateurs'
        );
    }

    public static function getValueCategorie($value) {
        switch ($value) {
            case '0':
                return 'Gestion des déchets';
            break;
            case '1':
                return 'Offre des acteurs économiques';
            break;
            case '2':
                return 'Demande et comportement des consommateurs';
            break;
            default:
                return '';
        }
    }
}
