<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * PilierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilierRepository extends \Doctrine\ORM\EntityRepository
{
}
