<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findRessourcesLike( $term, $limit = 10 )
    {

        $qb = $this->createQueryBuilder('x');
        $qb ->select('x.libelle')
            ->where('x.libelle LIKE :term')
            ->setParameter('term', $term.'%')
            ->orderBy('x.libelle')
            ->setMaxResults($limit);

        $arrayAss= $qb->getQuery()
            ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach($arrayAss as $data)
        {
            $array[] = array("Ressources"=>$data['libelle']);
        }

        return $array;
    }
    
}
