<?php

namespace Geolocation\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{

    public function findRessourcesLike($term, $limit = 10)
    {

        $qb = $this->createQueryBuilder('x');
        $qb->select('x.libelle')
            ->where('x.libelle LIKE :term')
            ->setParameter('term', $term . '%')
            ->orderBy('x.libelle')
            ->setMaxResults($limit);

        $arrayAss = $qb->getQuery()
            ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = array("Ressources" => $data['libelle']);
        }

        return $array;
    }

    public function findByUserExist()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->join('GeolocationAdminBundle:Cpf', 'c', 'WITH', 's.id = c.section')
            ->join('GeolocationAdminBundle:Ressources', 'r', 'WITH', 'c.id = r.cpf')
            ->groupBy('s.id');
        
        return $qb->getQuery()->getResult();
    }

}
