<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * SiteIsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteIsoRepository extends \Doctrine\ORM\EntityRepository
{
}
