<?php

namespace Geolocation\AdminBundle\Repository;

/**
 * SuppressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuppressionRepository extends \Doctrine\ORM\EntityRepository
{
}
