<?php

namespace Geolocation\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleFranceRepository extends EntityRepository
{

    public function findVillesLike($term, $limit = 10)
    {

        $qb = $this->createQueryBuilder('v');
        $qb->select('v.villeNomReel')
            ->where('v.villeNom LIKE :term')
            ->orWhere('v.villeNom LIKE :termNoSpace')
            ->setParameters(['term' => '%' . $term . '%', 'termNoSpace' => '%' . str_replace(' ', '-', $term) . '%'])
            ->orderBy('v.villePopulation2012', 'DESC')
            ->setMaxResults($limit);

        $arrayAss = $qb->getQuery()
            ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = array("Ville" => $data['villeNomReel']);
        }

        return $array;
    }


    public function findCodePostalFromCity($term)
    {
        $qb = $this->createQueryBuilder('v');
        $qb->select('v.villeCodePostal')
            ->where('v.villeNomReel LIKE :term')
            ->setParameter('term', $term . '%')
            ->orderBy('v.villeNom');

        $arrayAss = $qb->getQuery()
            ->getArrayResult();

        // Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach ($arrayAss as $data) {
            $array[] = array("CodePostal" => $data['villeCodePostal']);
        }

        return $array;
    }


}
