site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

geolocation_user:
    resource: "@GeolocationUserBundle/Resources/config/routing.yml"
    prefix:   /

geolocation_admin:
    resource: "@GeolocationAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

