geolocation_user:
    resource: "@GeolocationUserBundle/Resources/config/routing.yml"
    prefix:   /user

geolocation_admin:
    resource: "@GeolocationAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

