security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me:  true
                always_use_default_target_path : false
                use_referer: true
            remember_me:
                key:      %secret%
                lifetime: 31536000
                path:     /
                domain:   ~
            logout:       true
            anonymous:    true
            switch_user: true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ressources-ajout, role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/show-ressources, role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/change-password, role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/show-site, role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/profile, role: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/admin/*, role: ROLE_SUPER_ADMIN }

security:
    firewalls:
        main:
            pattern: ^/
            anonymous: true