adresse:
    pattern:  /
    defaults: { _controller: "GeolocationAdminBundle:Adresse:index" }

adresse_show:
    pattern:  /{id}/show
    defaults: { _controller: "GeolocationAdminBundle:Adresse:show" }

adresse_new:
    pattern:  /new
    defaults: { _controller: "GeolocationAdminBundle:Adresse:new" }

adresse_create:
    pattern:  /create
    defaults: { _controller: "GeolocationAdminBundle:Adresse:create" }
    requirements: { _method: post }

adresse_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GeolocationAdminBundle:Adresse:edit" }

adresse_update:
    pattern:  /{id}/update
    defaults: { _controller: "GeolocationAdminBundle:Adresse:update" }
    requirements: { _method: post|put }

adresse_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GeolocationAdminBundle:Adresse:delete" }
    requirements: { _method: post|delete }
