fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

pre_register:
    defaults: { _controller: GeolocationUserBundle:Registration:preRegister }
    path: /choisissez-votre-organisme

ajax_division:
    defaults: { _controller: GeolocationUserBundle:Ajax:getDivision }
    path: /ajax/getDivision

ajax_groupe:
    defaults: { _controller: GeolocationUserBundle:Ajax:getGroupe }
    path: /ajax/getGroupe

ajax_classe:
    defaults: { _controller: GeolocationUserBundle:Ajax:getClasse }
    path: /ajax/getClasse

ajax_categorie:
    defaults: { _controller: GeolocationUserBundle:Ajax:getCategorie }
    path: /ajax/getCategorie

ajax_sous_categorie:
    defaults: { _controller: GeolocationUserBundle:Ajax:getSousCategorie }
    path: /ajax/getSousCategorie
    
user_ressources:
    defaults: { _controller: GeolocationUserBundle:Ressources:edit }
    path: /ressources-ajout

user_ressources_delete : 
    defaults: { _controller: GeolocationUserBundle:Ressources:delete }
    path: /ressources-delete/{id}
    requirements:
        id: \d+