site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Index:index }

site_api_filter_ajax_ressources:
    path:     /ajax/json/get-entreprise-by-ressources
    defaults: { _controller: SiteBundle:Filtres:getEntrepriseByRessources }

site_details:
    path:     /details/{id}
    defaults: { _controller: SiteBundle:Details:details }
    
site_aide:
    path:     /aide
    defaults: { _controller: SiteBundle:Aide:aide }

site_contact:
    path:     /contact
    defaults: { _controller: SiteBundle:Contact:contact }
    
site_partenaires:
    path:     /partenaires
    defaults: { _controller: SiteBundle:Partenaires:partenaires }
    
site_apropos:
    path:     /apropos
    defaults: { _controller: SiteBundle:Apropos:apropos }
    
api_commun_json_villes:
    path: /json/getcities
    defaults: { _controller: SiteBundle:Index:getCities }
    
api_commun_json_ressources:
    path: /json/getressources
    defaults: { _controller: SiteBundle:Index:getRessources }
    
api_commun_json_entreprise:
    path: /json/getentreprise
    defaults: { _controller: SiteBundle:Index:getEntreprise }

api_markers:
    path: /json/markers
    defaults: { _controller: SiteBundle:Index:loadMarkers, _format: json }
    
searchCPfromCity:
    path: /json/getcodepostalfromcity
    defaults: { _controller: SiteBundle:Index:getCodepostalFromCity }
