services:
    site_bundle.filter_by_cpf:
        class: Geolocation\AdminBundle\Domain\Services\FilterByCpf
        arguments: ["@doctrine"]

    site_bundle.filter_by_city:
        class: Geolocation\AdminBundle\Domain\Services\FilterByCity
        arguments: ["@doctrine"]

    site_bundle.filter_by_code_postal:
        class: Geolocation\AdminBundle\Domain\Services\FilterByCodePostal
        arguments: ["@doctrine"]

    site_bundle.filter_by_nom_entreprise:
        class: Geolocation\AdminBundle\Domain\Services\FilterByNomEntreprise
        arguments: ["@doctrine"]

    site_bundle.calculate_distance_from_position:
        class: Geolocation\AdminBundle\Domain\Services\CalculateDistanceFromPosition
        arguments: ["@doctrine"]

    site_bundle.generate_array_ressources:
        class: Geolocation\AdminBundle\Domain\Services\GenerateArrayRessources
        arguments:
            - "@doctrine"
            - "@site_bundle.calculate_distance_from_position"
            - "@security.authorization_checker"
            - "@security.token_storage"

    site_bundle.generate_array_ressources_from_filters:
        class: Geolocation\AdminBundle\Domain\Services\GenerateArrayRessourcesFromFilters
        arguments:
            - "@doctrine"
            - "@site_bundle.filter_by_city"
            - "@site_bundle.filter_by_code_postal"
            - "@site_bundle.filter_by_cpf"
            - "@site_bundle.filter_by_nom_entreprise"
            - "@security.authorization_checker"
            - "@security.token_storage"
