geolocation_admin_pilier:
    resource: "@GeolocationAdminBundle/Resources/config/routing/pilier.yml"
    prefix:   /pilier

geolocation_admin_homepage:
    path:     /
    defaults: { _controller: GeolocationAdminBundle:Default:index }
